//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingSystem.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public long trans_id { get; set; }
        public System.DateTime create_datetime { get; set; }
        public long buy_order_id { get; set; }
        public long sell_order_id { get; set; }
        public int dealed { get; set; }
        public int stock_id { get; set; }
        public decimal deal_price { get; set; }
        public int type { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual orders orders1 { get; set; }
        public virtual stocks stocks { get; set; }
    }
}
