//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingSystem.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_positions
    {
        public long user_id { get; set; }
        public int stock_id { get; set; }
        public int num_free { get; set; }
        public int num_freezed { get; set; }
    
        public virtual stocks stocks { get; set; }
        public virtual users users { get; set; }
    }
}
